'use client';
import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';

export default function AuthPanel({mode}:{mode:'signin'|'register'}){
 const register=mode==='register'; const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
 useEffect(()=>{if(new URLSearchParams(window.location.search).get('error')==='google-not-configured')setMessage('Google sign-in is ready to connect. Add your OAuth client settings to enable it.')},[]);
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const data=new FormData(event.currentTarget);const password=String(data.get('password')||'');const confirm=String(data.get('confirm')||'');if(register&&!data.get('terms')){setMessage('Please accept the workspace terms to create an account.');setBusy(false);return}if(register&&password!==confirm){setMessage('Those passwords do not match.');setBusy(false);return}const email=String(data.get('email')||'');if(!email||password.length<8){setMessage('Enter a valid email and a password with at least 8 characters.');setBusy(false);return}sessionStorage.setItem('devops-demo-profile',JSON.stringify({email,name:String(data.get('name')||'Engineer')}));setMessage(register?'Demo profile is ready. Your credentials stay in this browser.':'Demo sign-in validated. Connect Google OAuth to use a real workspace account.');setBusy(false)}
 return <main className="auth-page"><header className="auth-nav"><Link href="/" className="brand"><span className="mark">⌘</span>DevOps Copilot</Link><div><span>{register?'Already have an account?':'Need an account?'}</span> <Link href={register?'/signin':'/register'}>{register?'Sign in':'Create account'}</Link></div></header><section className="auth-layout"><div className="auth-story"><div className="eyebrow">CALMER ON-CALL STARTS HERE</div><h1>{register?'Build a calmer on-call.':'Welcome back to a calmer on-call.'}</h1><p>Bring your alerts, runbooks and teams into one clear incident workspace.</p><div className="auth-benefits"><span>✓ Runbook-aware incident analysis</span><span>✓ Read-only by default</span><span>✓ Clear handoffs and audit history</span></div></div><div className="auth-card"><div className="auth-tabs"><Link className={!register?'selected':''} href="/signin">Sign in</Link><Link className={register?'selected':''} href="/register">Create account</Link></div><h2>{register?'Create your account':'Sign in to your workspace'}</h2><p className="auth-sub">{register?'Start with a secure demo workspace.':'Use your work email and password to continue.'}</p><form onSubmit={submit}>{register&&<label>Full name<input name="name" autoComplete="name" placeholder="Alex Morgan" required/></label>}<label>Work email<input name="email" type="email" autoComplete="email" placeholder="you@company.com" required/></label><label>Password<input name="password" type="password" autoComplete={register?'new-password':'current-password'} placeholder="At least 8 characters" minLength={8} required/></label>{register&&<><label>Confirm password<input name="confirm" type="password" autoComplete="new-password" placeholder="Repeat your password" minLength={8} required/></label><label className="terms-check"><input type="checkbox" name="terms" required/> I agree to the workspace terms and privacy policy.</label></>}{!register&&<div className="auth-help"><label className="remember"><input type="checkbox"/> Remember me</label><a href="mailto:help@devopscopilot.example?subject=Password%20reset">Forgot password?</a></div>}<button className="button dark auth-submit" disabled={busy}>{busy?'Please wait…':register?'Create account':'Sign in'} <span>→</span></button></form>{message&&<p className="auth-message" role="status">{message}</p>}<div className="auth-divider"><span>OR CONTINUE WITH</span></div><a className="google-button" href={`/api/auth/google?intent=${mode}`}><GoogleIcon/>Continue with Google</a><p className="auth-terms">{register?'Demo account setup is local to this browser.':'Demo form validates locally. Passwords are not stored or sent.'}</p></div></section><footer className="auth-footer">© 2026 DevOps Copilot <span>Privacy · Security · Help</span></footer></main>
}
function GoogleIcon(){return <svg aria-hidden="true" viewBox="0 0 48 48"><path fill="#FFC107" d="M43.6 24.5c0-1.4-.1-2.8-.4-4.1H24v7.8h11a9.5 9.5 0 0 1-4.1 6.2v5.1h6.7c3.9-3.6 6-8.8 6-15Z"/><path fill="#FF3D00" d="M24 44c5.4 0 9.9-1.8 13.2-4.8l-6.7-5.1c-1.8 1.2-4 1.9-6.5 1.9-5.1 0-9.4-3.4-10.9-8H6.2v5.3A20 20 0 0 0 24 44Z"/><path fill="#4CAF50" d="M13.1 28a12 12 0 0 1 0-8v-5.3H6.2a20 20 0 0 0 0 18.6l6.9-5.3Z"/><path fill="#1976D2" d="M24 12c2.9 0 5.4 1 7.4 3l5.9-5.9A19.7 19.7 0 0 0 24 4 20 20 0 0 0 6.2 14.7l6.9 5.3C14.6 15.4 18.9 12 24 12Z"/></svg>}
