'use client';
import Image from 'next/image';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { useEffect, useState } from 'react';

const logos = ['Corebit','Lumen Labs','Aerix','Flare','Vault','Driftwave','Northstar','Knot'];
const features = [
  ['Diagnose in seconds','Copilot reads logs, metrics and deploys the moment an alert fires.','simple-diagnose'],
  ['Learn from your runbooks','It learns from your runbooks, postmortems and past incidents — no setup required.','simple-runbooks'],
  ['Know when to escalate','For risky or ambiguous incidents, Copilot pages the right engineer with full context.','simple-handoff']
];
const whys = [
  ['It gets smarter with every incident it sees','Copilot learns from every resolved incident, picking up patterns and edge cases so it can find the signal faster.','blend-metrics.svg'],
  ['It always follows your runbooks','Your team’s procedures guide every recommendation, with a clear audit trail for every action.','blend-response.svg'],
  ['It clears your overnight alert queue for you','Routine incidents are handled while your team sleeps, so mornings start with a clear queue.','blend-analytics.svg']
];
const tabs: [string,string,string[]][] = [
 ['Alert triage','Every alert, sorted the moment it fires.',['Instant categorization|Classify by service, symptom and environment as alerts arrive.','Priority that makes sense|Map impact to clear SEV1–SEV4 severity.','Zero manual sorting|Route each alert to the right on-call engineer.']],
 ['Root-cause analysis','Find the cause before the incident spreads.',['Correlate signals|Connect logs, metrics, traces and deploys.','See the timeline|Understand what changed and when.','Fix with confidence|Get a practical, evidence-backed next step.']],
 ['Smart handoff','The right engineer gets the full picture.',['Route by ownership|Find the team responsible for the service.','Preserve context|Pass along evidence, impact and actions tried.','Escalate with care|Page a human when confidence is low.']],
 ['Live reporting','Know what is happening across your stack.',['Track incidents|See live status across every service.','Spot patterns|Surface repeat causes and noisy alerts.','Share outcomes|Keep stakeholders aligned with clear updates.']]
];
const faqs = [
 ['How is this different from a generic chatbot?','DevOps Copilot is grounded in your telemetry, deployment history and runbooks. It reasons over incident evidence and is explicit when it needs a human.'],
 ['How many incidents can it resolve on its own?','It can safely handle routine, well-understood incidents when you enable those actions. Higher-risk or ambiguous incidents are escalated to your on-call team.'],
 ['Is my infrastructure data private?','Yes. Credentials are scoped, access is read-only by default, and secrets stay in your environment. Every action is recorded in an audit log.'],
 ['Does it adapt to our stack?','Copilot learns your services, ownership and runbooks as you connect your existing tools. No custom model training is required.'],
 ['Which tools does it integrate with?','PagerDuty, Slack, GitHub, Datadog, Kubernetes and AWS, with more integrations on the way.'],
 ['Can I turn off auto-remediation?','Absolutely. Keep Copilot in recommend-only mode, require approval for each action, or enable remediation only for the cases you choose.']
];
const reveal = { hidden:{opacity:0,y:24,filter:'blur(8px)'}, show:{opacity:1,y:0,filter:'blur(0px)',transition:{duration:.7,ease:[.22,1,.36,1] as const}} };
function Mark(){return <span className="mark">⌘</span>}
function Nav(){const [open,setOpen]=useState(false);return <header className="nav"><Link className="brand" href="/"><Mark/>DevOps Copilot</Link><nav className={open?'nav-open':''}><a href="#why" onClick={()=>setOpen(false)}>Company⌄</a><a href="#integrations" onClick={()=>setOpen(false)}>Integrations</a><a href="#customers" onClick={()=>setOpen(false)}>Customers</a><Link className="nav-mobile-signin" href="/signin" onClick={()=>setOpen(false)}>Sign In</Link></nav><div className="nav-right"><Link href="/signin">Sign In</Link><Link className="button dark small" href="/solve">Let’s solve <span>↗</span></Link><button className="menu" aria-label="Open menu" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'×':'☰'}</button></div></header>}
function CompanyMark({name}:{name:string}){const paths:Record<string,React.ReactNode>={Corebit:<><circle cx="12" cy="12" r="9"/><path d="M7 12h10M12 7v10" stroke="white" strokeWidth="2"/></>,"Lumen Labs":<><circle cx="12" cy="12" r="3"/><path d="M12 2v4m0 12v4M2 12h4m12 0h4M5 5l3 3m8 8 3 3m0-14-3 3m-8 8-3 3" stroke="currentColor" strokeWidth="2"/></>,Aerix:<path d="M12 2 23 21H1z"/>,Flare:<path d="m12 1 2.8 7.2L22 5l-3.2 7 4.2 5.8-7.8-.2L12 24l-3-7.4-8-.2 5-5.8L3 4l7 3z"/>,Vault:<><path d="M12 1 22 7v10l-10 6L2 17V7z"/><circle cx="12" cy="12" r="3" fill="white"/></>,Driftwave:<path d="M2 8q5-5 10 0t10 0M2 13q5-5 10 0t10 0M2 18q5-5 10 0t10 0" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/>,Northstar:<path d="m12 1 2.2 8.8L23 12l-8.8 2.2L12 23l-2.2-8.8L1 12l8.8-2.2z"/>,Knot:<><circle cx="9" cy="12" r="6" fill="none" stroke="currentColor" strokeWidth="2.5"/><circle cx="15" cy="12" r="6" fill="none" stroke="currentColor" strokeWidth="2.5"/></>};return <svg className="company-symbol" viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg>}
function Marquee(){return <div className="marquee"><div className="marquee-track">{[...logos,...logos].map((x,i)=><span className="company-logo" key={`${x}-${i}`}><CompanyMark name={x}/>{x}</span>)}</div></div>}
function Art({image,alt="Product interface preview",className=""}:{image:string;alt?:string;className?:string}){if(image.startsWith('simple-'))return <div className={`art feature-art ${className}`}><Image src="/images/meadow.jpg" alt="" fill className="paint" sizes="(max-width: 800px) 100vw, 70vw"/><FeaturePreview variant={image.replace('simple-','')}/></div>;if(image.startsWith('usecase-')||image.startsWith('cta-'))return <div className={`art custom-art ${className}`}><Image src={`/images/${image}`} alt={alt} fill sizes="(max-width: 800px) 100vw, 50vw"/></div>;return <div className={`art ${className}`}><Image src="/images/meadow.jpg" alt="" fill className="paint" sizes="(max-width: 800px) 100vw, 70vw"/><Image src={`/images/${image}`} alt={alt} width={1200} height={700} className={image.startsWith('feature-')||image.startsWith('blend-')?'source-shot custom-feature-shot':'source-shot'} sizes="(max-width: 800px) 100vw, 50vw"/></div>}
function FeaturePreview({variant}:{variant:string}){return <div className={`feature-preview preview-${variant}`}><header className="feature-preview-head"><span className="preview-brand-mark">⌘</span><b>DevOps Copilot</b><span className="preview-live"><i/> Live</span></header><div className="feature-preview-body">{variant==='diagnose'&&<><div className="preview-heading"><b>Incident inbox</b><small>Updated just now</small></div><div className="preview-metrics"><div><small>Active incidents</small><b>08</b></div><div><small>Services healthy</small><b>24/26</b></div><div><small>MTTR today</small><b>6m 42s</b></div></div><div className="preview-table-head"><span>Incident</span><span>Service</span><span>Status</span></div><div className="preview-table-row"><b><i className="preview-sev red"/>5xx spike after deploy</b><span>checkout-api</span><em>Investigating</em></div><div className="preview-table-row"><b><i className="preview-sev amber"/>Worker memory pressure</b><span>worker-queue</span><em>Analyzing</em></div></>}{variant==='runbooks'&&<><div className="preview-heading"><b>Runbook guidance</b><small>Matched to this incident</small></div><div className="preview-recommend"><span>✓</span><div><b>Worker queue recovery</b><small>Recommended · 94% match</small></div></div><div className="preview-step"><span>01</span><b>Check recent worker restarts</b><em>Complete</em></div><div className="preview-step"><span>02</span><b>Review memory limits</b><em>Next step</em></div><div className="preview-footnote">Production changes always require your approval.</div></>}{variant==='handoff'&&<><div className="preview-heading"><b>Escalation handoff</b><small>Context included</small></div><div className="preview-alert"><b>Human review recommended</b><span>Provider status is unclear. We’ve paused automatic action.</span></div><div className="preview-person"><span>MC</span><div><b>Morgan Chen</b><small>Payments on-call · Available</small></div><em>Best match</em></div><div className="preview-context"><span>Alert timeline</span><span>Recent deploy</span><span>Related runbook</span></div></>}</div></div>}
function HeroPreview(){return <div className="hero-preview"><Image src="/images/meadow.jpg" alt="Painted wildflower meadow" fill priority className="hero-paint" sizes="(max-width: 800px) 100vw, 90vw"/><div className="hero-dashboard"><div className="dash-top"><span className="dash-dot"/> DEVOPS COPILOT <span className="dash-more">•••</span></div><div className="dash-body"><aside className="dash-rail"><b>DC</b><i>▦</i><i>⌁</i><i>◷</i><i>⌘</i></aside><div className="dash-main"><div className="dash-heading">Incident inbox <small>Live · Updated now</small></div><div className="dash-metrics"><div><small>Active incidents</small><b>08</b></div><div><small>Services healthy</small><b>24/26</b></div><div><small>MTTR today</small><b>6m 42s</b></div></div><div className="dash-columns dash-header"><span>INCIDENT</span><span>SERVICE</span><span>SEVERITY</span><span>STATUS</span></div>{[['5xx spike after deploy','checkout-api','SEV1','Investigating'],['Pod CrashLoopBackOff','worker-queue','SEV2','Analyzing'],['DB connection pool exhausted','orders-db','SEV1','Escalated']].map((row,i)=><div className="dash-columns dash-row" key={row[0]}><span><i className={`dash-sev s${i}`}/>{row[0]}</span><span>{row[1]}</span><span><em className={`dash-pill s${i}`}>{row[2]}</em></span><span className="dash-status">{row[3]}</span></div>)}</div></div></div></div>}
export default function Home(){
 return <><Nav/><main>
  <section className="hero"><motion.div className="hero-copy" initial="hidden" animate="show" variants={{show:{transition:{staggerChildren:.1}}}}><motion.div variants={reveal} className="announce"><i/> NEW&nbsp;&nbsp; Auto-remediation is now live <span className="announce-arrow">→</span></motion.div><motion.h1 variants={reveal}>The incident response agent that never sleeps.</motion.h1><motion.p variants={reveal}>An AI on-call copilot that triages alerts, finds the root cause in seconds — and knows exactly when to page your team.</motion.p><motion.div variants={reveal}><Link href="/solve" className="button dark">Let’s solve <span>↗</span></Link></motion.div></motion.div><motion.div className="hero-art" initial={{opacity:0,y:35}} animate={{opacity:1,y:0}} transition={{duration:.8,delay:.3}}><HeroPreview/></motion.div></section>
  <Marquee/>
  <section className="section feature-section" id="what"><div className="eyebrow">What DevOps Copilot does</div><h2>Three ways Copilot<br/><em>runs your incidents.</em></h2><div className="feature-grid">{features.map(([title,desc,img],i)=><motion.article className="feature-card" key={title} initial="hidden" whileInView="show" viewport={{once:true,amount:.18}} variants={reveal}><Art image={img}/><div className="feature-number">0{i+1}</div><h3>{title}</h3><p>{desc}</p></motion.article>)}</div></section>
  <section className="section why-section" id="why"><div className="eyebrow">Why DevOps Copilot</div><h2>One console.<br/><em>Every incident, handled.</em></h2><div className="why-stack">{whys.map(([title,desc,img],i)=><article className="why-card" key={title} style={{top:`${100+i*26}px`,zIndex:i+1}}><div className="why-copy"><div className="eyebrow">0{i+1} / Built for the on-call</div><h3>{title}</h3><p>{desc}</p><Link className="button dark" href="/solve">Get started <span>↗</span></Link></div><Art image={img}/></article>)}</div></section>
  <section className="section use-section" id="use-cases"><div className="eyebrow">Use cases</div><h2>One platform.<br/><em>Every team it touches.</em></h2><UseCases/></section>
  <section className="section security" id="security"><div className="security-intro"><div className="eyebrow">Security</div><h2>Enterprise-grade security,<br/><em>built in by default.</em></h2><p>Infrastructure access designed for the teams who protect production.</p></div><div className="security-grid">{[['◉','Proven compliance','Detailed audit logs for every recommendation and action.'],['⌖','Full control','Read-only access by default, with scoped credentials.'],['◇','End-to-end encryption','Data is encrypted in transit and at rest.'],['↗','Your data','Secrets never leave your environment.']].map(([icon,title,desc])=><div className="security-item" key={title}><span>{icon}</span><h3>{title}</h3><p>{desc}</p></div>)}</div></section>
  <section className="section used" id="integrations"><div className="eyebrow">Built for engineering teams</div><h2>Works with the tools<br/><em>your team already uses.</em></h2><Marquee/><div className="integration-grid">{[['PagerDuty','Route critical alerts to the right on-call rotation.','◉'],['Slack','Share incident timelines and handoffs in team channels.','#'],['GitHub','Correlate releases, pull requests and deployment changes.','⌘'],['Datadog','Ground analysis in metrics, traces and service health.','◒'],['Kubernetes','Connect cluster events, pod health and workload signals.','⎈'],['AWS','Bring cloud alerts and account context into one view.','⌁']].map(([name,desc,icon])=><article className="integration-card" key={name}><span>{icon}</span><div><b>{name}</b><p>{desc}</p></div><i>Connected-ready</i></article>)}</div></section>
  <section className="results" id="customers"><div className="quote-card"><div className="quote-icon">“</div><p>We used to start every morning buried in alerts. Now we start with a clear picture of what happened and what needs our attention.</p><div className="quote-by"><span className="avatar purple">AM</span><div><b>Alex Morgan</b><small>VP Engineering, Northstar</small></div></div></div><div className="stats"><Stat label="Auto-triaged incidents" value={78} suffix="%"/><Stat label="Lower mean time to resolve" value={42} suffix="%"/><Stat label="On-call satisfaction" value={4.8} suffix="/5" decimal/></div></section>
  <section className="section love"><div className="eyebrow">Loved by on-call teams</div><h2>Less pager fatigue,<br/><em>more breathing room.</em></h2><div className="testimonials">{[['“We can finally focus on fixing the system instead of sorting alerts all night.”','Priya S.','SRE Lead'],['“The handoff gives us the whole story. No more hunting through five tools.”','Jordan K.','Platform Engineer'],['“Runbook-first automation makes our on-call rotation feel manageable again.”','Sam R.','Engineering Manager']].map(([q,n,r])=><article key={n}><div className="stars">★★★★★</div><p>{q}</p><b>{n}</b><small>{r}</small></article>)}</div></section>
  <section className="section faq"><div className="faq-title"><div className="eyebrow">FAQ</div><h2>You have questions.<br/><em>We have answers.</em></h2><p>Everything you need to know about your new on-call copilot.</p></div><div className="faq-list">{faqs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  <section className="final-cta"><div><div className="eyebrow">Your next on-call starts here</div><h2>Give your on-call team<br/>their nights back.</h2><p>Let Copilot handle the noise. Keep your team focused on what matters.</p><Link href="/solve" className="button dark">Let’s solve <span>↗</span></Link></div><div className="final-art"><Art image="cta-board.svg" alt="DevOps Copilot reliability overview"/></div></section>
 </main><footer className="footer"><div className="footer-brand"><Link className="brand" href="/"><Mark/>DevOps Copilot</Link><p>Calmer incidents.<br/>Better engineering.</p></div><div><b>Product</b><a href="#what">What it does</a><a href="#use-cases">Use cases</a><Link href="/solve">Incident inbox</Link></div><div><b>Explore</b><a href="#why">Why Copilot</a><a href="#customers">Customers</a><a href="#integrations">Integrations</a></div><div><b>Company</b><a href="#security">Security</a><Link href="/signin">Sign in</Link><a href="mailto:hello@devopscopilot.example">Contact</a></div><div className="copyright">© 2026 DevOps Copilot.<span>LinkedIn&nbsp;&nbsp; ↗ &nbsp;&nbsp;GitHub&nbsp;&nbsp; ↗</span></div></footer></>;
}
function UseCases(){const [active,setActive]=useState(0);const images=['blend-inbox.svg','usecase-cause.svg','usecase-handoff.svg','usecase-live.svg'];return <div className="usecase"><div className="tabs">{tabs.map(([name],i)=><button key={name} className={active===i?'active':''} onClick={()=>setActive(i)}>{name}</button>)}</div><motion.div className="usecase-content" key={active} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{duration:.35}}><div className="usecase-copy"><h3>{tabs[active][1]}</h3>{tabs[active][2].map((item)=><div className="use-bullet" key={item}><span>✓</span><div><b>{item.split('|')[0]}</b><p>{item.split('|')[1]}</p></div></div>)}<Link href="/solve" className="button dark">Let’s solve <span>↗</span></Link></div><Art image={images[active]} alt={`${tabs[active][0]} visualization`}/></motion.div></div>}
function Stat({label,value,suffix,decimal=false}:{label:string;value:number;suffix:string;decimal?:boolean}){const [shown,setShown]=useState(0);useEffect(()=>{const start=performance.now(),duration=1300;let raf=0;const step=(now:number)=>{const t=Math.min(1,(now-start)/duration),eased=1-Math.pow(1-t,3);setShown(value*eased);if(t<1)raf=requestAnimationFrame(step)};raf=requestAnimationFrame(step);return()=>cancelAnimationFrame(raf)},[value]);return <div><small>{label}</small><strong>{decimal?shown.toFixed(1):Math.round(shown)}<span>{suffix}</span></strong><i>↑ Sample result</i></div>}
